language: python

# testing python versions
python:
#  - "3.5"
  - "3.6"

# install dependencies
before_install:

  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pip
  - source activate test-environment
  - pip install -r requirements.txt
  - pip install git+https://github.com/weddige/miniball
  - conda install -c conda-forge gudhi 

# install dowker_homology
install:
  - python setup.py install

# run tests
script: python -m pytest --count 2
