name: dowker
channels:
  - conda-forge
dependencies:
  - python=3.6
  - gudhi
  - nbconvert
  - nbformat
  - nbsphinx
  - pycparser
  - git
  - matplotlib
  - nb_conda
  - networkx
  - numpy
  - pandas
  - pip
  - pytest
  - scikit-learn
  - scipy
  - setuptools
  - sphinx
  - pip:
    - persim
    - pynverse
    - pytest-repeat
    - git+https://github.com/weddige/miniball.git
