name: dowker
channels:
  - conda-forge
  - defaults
dependencies:
  - gudhi=2.3.0=py36h83d4a3d_0
  - nbconvert=5.3.1=py_1
  - nbformat=4.4.0=py_1
  - nbsphinx=0.4.2=py_0
  - pycparser=2.19=py_0
  - git=2.19.1=pl526hacde149_0
  - matplotlib=3.0.2=py36h5429711_0
  - nb_conda=2.2.1=py36_0
  - nb_conda_kernels=2.2.0=py36_0
  - networkx=2.2=py36_1
  - numpy=1.15.4=py36h7e9f1db_0
  - pandas=0.23.4=py36h04863e7_0
  - pip=18.1=py36_0
  - pytest=4.1.0=py36_0
  - scikit-learn=0.20.2=py36hd81dba3_0
  - scipy=1.1.0=py36h7c811a0_2
  - setuptools=40.6.3=py36_0
  - sphinx=1.8.2=py36_0
  - pip:
    - hopcroftkarp==1.2.4
    - miniball==0.2
    - persim==0.0.7
    - pynverse==0.1.4.4
    - pytest-repeat==0.7.0

