name: dowker
channels:
  - conda-forge
dependencies:
  - python=3.6
  - gudhi
  - matplotlib
  - networkx
  - nbsphinx
  - numpy
  - pandas
  - pytest
  - scikit-learn
  - scipy
  - setuptools
  - pip:
    - persim
    - pynverse
    - git+https://github.com/weddige/miniball.git
